//! Channel public inputs for zero-knowledge proof verification
//!
//! This module defines the public inputs structure for channel transition proofs.

use bitcoin::secp256k1::XOnlyPublicKey;

use crate::types::{ChannelCommitment, ChannelId};

/// Channel public inputs structure
///
/// Public inputs for channel transition proof verification. This struct contains only
/// public values that are committed in the proof. These values are revealed to the
/// verifier and must match what is attested in the zero-knowledge proof.
///
/// The `sender_pubkey` field is included to enable sender authentication verification.
/// The verifier can check that the proof was generated by someone who knows the private
/// key corresponding to this public key, without revealing the private key itself.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ChannelPublicInputs {
    /// Channel identifier
    pub channel_id: ChannelId,
    /// Channel commitment (commitment to the new state)
    pub channel_commitment: ChannelCommitment,
    /// Sender's public key (Taproot X-only public key)
    ///
    /// This is used to verify that the proof was generated by the sender who knows
    /// the corresponding private key. The authentication hash in the proof binds
    /// the commitment to this public key cryptographically.
    pub sender_pubkey: XOnlyPublicKey,
}
